#!/bin/sh

### BEGIN INIT INFO
# Provides:          q1_ktx_dm
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: QuakeWorld KTX DM server
# Description:       Starts and stops the QuakeWorld KTX DM server
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=gameservers
COMMAND=/home/${USER}/$(basename "$0")
DESCRIPTION="QuakeWorld KTX DM"

. /lib/init/gameserver.sh $@
