#!/bin/sh

### BEGIN INIT INFO
# Provides:          q1_excoop
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts QuakeWorld co-op server
# Description:       This script starts the QuakeWorld co-op server
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=gameservers
COMMAND=/home/${USER}/$(basename "$0")
DESCRIPTION="QuakeWorld co-op"

. /lib/init/gameserver.sh $@
