#!/bin/sh

### BEGIN INIT INFO
# Provides:          q1_ktx_dm
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts QuakeWorld KTX DM server
# Description:       This script starts the QuakeWorld KTX DM server
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=$(basename "$0")
USER=gameservers
WORKINGDIR=/home/${USER}
PIDFILE=${WORKINGDIR}/${NAME}.pid
COMMAND=${WORKINGDIR}/${NAME}
DESCRIPTION="QuakeWorld KTX DM"

. /lib/init/gameserver.sh $@
