#!/bin/sh

### BEGIN INIT INFO
# Provides:          q3_cpma_arena
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Quake 3 CPMA Multi-Arena server
# Description:       This script starts the Quake 3 CPMA Multi-Arena server
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=gameservers
COMMAND=/home/${USER}/$(basename "$0")
DESCRIPTION="Quake 3 CPMA Multi-Arena"

. /lib/init/gameserver.sh $@
